### ISSUE TITLE
Issue creating fixations file based on Tobii Glasses 3 dataset

### ISSUE THREAD

**Issue by MarcelClaus** [uxifiit/GazeToolkit#36]
Our university owns a Tobii Glasses 3 50 hz eye-tracker. This device records timestamps in seconds with decimals. I'm having issues creating a fixation json file. I'm not sure if the issue is with my input json or the syntax i'm using. 

I've used the following Tobii Glasses 3 dataset:
[gazedata_TobiiGlasses3.json](https://github.com/uxifiit/GazeToolkit/files/15473710/gazedata_TobiiGlasses3.json)

The first line of this file is as follows:

`{"type":"gaze","timestamp":0.006751,"data":{"gaze2d":[0.39790000000000014,0.86000000000000032],"gaze3d":[61.710000000000015,-136.57000000000002,330.52000000000004],"eyeleft":{"gazeorigin":[31.740000000000006,-15.820000000000004,-33.000000000000007],"gazedirection":[0.077400000000000024,-0.30130000000000012,0.95040000000000036],"pupildiameter":3.4370000000000007},"eyeright":{"gazeorigin":[-29.110000000000007,-18.350000000000005,-34.010000000000005],"gazedirection":[0.23120000000000007,-0.31280000000000008,0.92130000000000034],"pupildiameter":3.3600000000000008}}}
`

I've converted this to a format as is mentioned in the ReadMe file. The Glasses 3 records in seconds so I've converted the Timestamp to miliseconds.  Here's the first line;

`[
{"Timestamp":6.751,"LeftEye":{"Validity":"Valid","GazePoint2D":{"X":0.3979,"Y":0.86},"GazePoint3D":{"X":61.71,"Y":-136.57,"Z":330.52},"EyePosition3D":{"X":31.74,"Y":-15.82,"Z":-33.0},"PupilDiameter":3.437},"RightEye":{"Validity":"Valid","GazePoint2D":{"X":0.3979,"Y":0.86},"GazePoint3D":{"X":61.71,"Y":-136.57,"Z":330.52},"EyePosition3D":{"X":-29.11,"Y":-18.35,"Z":-34.01},"PupilDiameter":3.36}},{"Timestamp":26.733,"LeftEye":{"Validity":"Valid","GazePoint2D":{"X":0.3932,"Y":0.8665},"GazePoint3D":{"X":66.46,"Y":-142.3,"Z":338.13},"EyePosition3D":{"X":31.84,"Y":-15.88,"Z":-33.05},"PupilDiameter":3.45},"RightEye":{"Validity":"Valid","GazePoint2D":{"X":0.3932,"Y":0.8665},"GazePoint3D":{"X":66.46,"Y":-142.3,"Z":338.13},"EyePosition3D":{"X":-29.04,"Y":-18.4,"Z":-34.08},"PupilDiameter":3.351}}
]`

[gaze_converted_for_GazeToolkit.json](https://github.com/uxifiit/GazeToolkit/files/15473686/gaze_converted_for_GazeToolkit.json)

I've use the following syntax;

`i-vt gaze.json --format JSON --timestamp-format ticks:ms --fillin --select Average --denoise --frequency 50 --merge --discard --discard-min-duration 10 --output output.json
`
However, the output file is empty and the console output only displays:

`Filter,InputSamples,OutputSamples,Runtime`

Any suggestions what to change would be welcome. Thank you for this project!

**Comment by martinkonopka** [comment]
Thanks for the report, I will look at it.

**Comment by martinkonopka** [comment]
HI @venkman-gh , I have figured it out. There are 2 issues:

**1. Timestamps should not be decimals but long integer values.** 

Example in the readme is incorrect, it should be like this, I will fix it: 
    * `date` - `2019-02-20T14:30:19.8526299+01:00`
    * `time` - `14:30:19.8526299`
    * `ticks:ns` (hundred nanoseconds) - `636862698198526299`
    * `ticks:us` (microseconds, e.g., from the epoch 01/01/1970) - **`1550669419852630`**
    * `ticks:ms` (milliseconds from the epoch 01/01/1970) - **`1550669419853`**
This is caused by the converter which converts the value to `Int64`: https://github.com/uxifiit/Filters/blob/fbfaf9f84234003b74fc00e02f2030a2ca1d858a/src/UXI.Filters/Serialization/Converters/TimestampFromTicksConverter.cs#L56C1-L56C45

I think you can use these formats in your case:
1. `time` - convert your timestamps to value of time, for example instead `0.006751` for 6.751ms in the sample file, it would be: `00:00:00.006751`, or
2. `ticks:us` - convert timestamps to microseconds, for example `6751`


**2. There must not be missing data for either eye**
For some samples, there is `null` for left or right eye in your data. For example: 
```
{"Timestamp":0.507603,"LeftEye":{"Validity":"Valid","GazePoint2D":{"X":0.3522,"Y":0.8903},"GazePoint3D":{"X":86.08,"Y":-137.47,"Z":305.99},"EyePosition3D":{"X":32.61,"Y":-16.1,"Z":-33.58},"PupilDiameter":3.592},"RightEye":null}
```
There must always be a structure for each eye. If the eye was not tracked, instead of `"RightEye":null`, use an "invalid" sample with `NaN` values. I agree this is not very clear from the readme, nor the program output. For example:
```
  {
    "Timestamp": 507603,
    "LeftEye": {
      "Validity": "Valid",
      "GazePoint2D": {
        "X": 0.3522,
        "Y": 0.8903
      },
      "GazePoint3D": {
        "X": 86.08,
        "Y": -137.47,
        "Z": 305.99
      },
      "EyePosition3D": {
        "X": 32.61,
        "Y": -16.1,
        "Z": -33.58
      },
      "PupilDiameter": 3.592
    },
    "RightEye": {
      "EyePosition3D": {
        "X": "NaN",
        "Y": "NaN",
        "Z": "NaN"
      },
      "PupilDiameter": "NaN",
      "Validity": "Invalid",
      "GazePoint2D": {
        "Y": "NaN",
        "X": "NaN"
      },
      "GazePoint3D": {
        "X": "NaN",
        "Y": "NaN",
        "Z": "NaN"
      }
    }
  }
```

After fixing these 2 issues in your data, I was able to run the filter. I have used this PowerShell script to fix your data:

```
Get-Content .\gaze_converted_for_GazeToolkit.json `
| ConvertFrom-Json `
| ForEach-Object `
    -Begin { 
        $nan = [Double]::NaN
        $unknown = @{ 
            "Validity" = "Invalid";
            "GazePoint2D" = @{ "X" = $nan; "Y" = $nan };
            "GazePoint3D" = @{ "X" = $nan; "Y" = $nan; "Z" = $nan };
            "EyePosition3D" = @{ "X" = $nan; "Y"= $nan; "Z" = $nan };
            "PupilDiameter" = $nan 
        } 
    } `
    -Process {
        $_.Timestamp = [System.Int64]($_.Timestamp * 1000 * 1000)
        if ($_.LeftEye -eq $NULL) {
            $_.LeftEye = $unknown 
        }
        if ($_.RightEye -eq $NULL) {
            $_.RightEye = $unknown
        } 
        $_ 
    } `
| ConvertTo-Json -Depth 10 `
| Set-Content .\gaze_fixed.json
```

Then, run the i-vt filter with `gaze_fixed.json`: 
```
i-vt gaze_fixed.json --timestamp-field Timestamp --timestamp-format ticks:us --fillin --select Average --denoise --frequency 50 --merge --discard --discard-min-duration 10 --output output.json

# Filter,InputSamples,OutputSamples,Runtime
# I-VT Fixation Filtering,2282,179,00:00:00.2925302
```
[output.json](https://github.com/user-attachments/files/15754132/output.json)

I also recommend to run the [filters individually](https://github.com/uxifiit/GazeToolkit?tab=readme-ov-file#fixation-filtering-with-individual-filters) (selecting eye, smoothing, merging, etc.) and observe the intermediate results. You can plot them and tweak the parameters as you like.

**Comment by MarcelClaus** [comment]
Thank you, I've tested your suggestions on different Tobii Glasses 3 datasets and was successfully able to determine the fixations. Thank you for supporting this project!

**Comment by martinkonopka** [comment]
Thank you for using the project, I am glad it helped, @venkman-gh
